### ISSUE TITLE
Enhancements 16-10-17

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/TvT_BreakingContact.Stratis#102]
- [x] Balancing Fahrzeuge?

Mehr Möglichkeiten für Opfor schaffen
zB ZSU23-Truck, tragbare Igla statt statischer Launcher

**Comment by McDiod** [comment]
- [ ] Raven Zeug aus dem Briefing entfernen.

https://github.com/gruppe-adler/TvT_BreakingContact.Stratis/blob/1759d5ae5cc00f98326f582729c97c8f21feb9cf/player/setup/helpBriefing.sqf#L34

**Comment by McDiod** [comment]
Vorschlag: Player Damage in den ACE Medical Settings runterschrauben (steht derzeit auf 3). Gestern hat jemand n Kopftreffer überlebt.

Ich glaube das ist ein wesentlicher Faktor, warum Opfor in letzter Zeit so wenig gewinnt. Hit and Run funktioniert nicht mehr, weil die Gegner nicht sterben. Um sie zu töten, wenn sie dann bewusstlos auf dem Boden liegen, fehlt die Zeit, weil man direkt von 3+ Mann Gegenfeuer bekommt.

**Comment by nomisum** [comment]
hm, das soll eigentlich dazu führen, dass man nicht instastirbt (mir trotzdem in der letzten runde passiert btw). prevent insta death war auch nicht wirklich bugfrei leider (1s bewusstlos und wieder up).

gab es montag ne situation, in der hit&run funktioniert hätte? ich hatte nicht das gefühl dass blufor die halbe truppe gesundflicken musste/getan hat. (was früher mit prevent instant death auch schon recht oft passiert ist imo)

**Comment by McDiod** [comment]
Immer eigentlich. Also ich rede nicht von Opfors Gesamttaktik für's Spiel, sondern darüber, was jeder einzelne Spieler im Kampf macht. Wenn ich mehr oder weniger alleine bin und 4 Gegner vor mir habe, würde ich normalerweise schnell ein paar Schüsse abgeben und mich dann zurückziehen / die Position ändern. Bringt nur nichts, weil die Gegner meistens mindestens einmal, manchmal sogar zweimal angeschossen und bewusstlos werden können, bevor sie sterben.

**Comment by nomisum** [comment]
> Bringt nur nichts, weil die Gegner meistens mindestens einmal, manchmal sogar zweimal angeschossen und bewusstlos werden können, bevor sie sterben.
Hm, ich würde das eher als Feature sehen als als Bug? Finde es gut, wenn nicht jeder Treffer tödlich ist.

Können da aber gern tweaken, evtl erstma auf Damage 2 oder so. Hoffe eigentlich auch auf ein paar neue Features bei ACE bzgl Bewusstlosigkeit und Auswirkungen von Treffern nach dem Medical Rewrite (also eher mittelfristig/langfristig).

**Comment by nomisum** [comment]
https://github.com/gruppe-adler/TvT_BreakingContact.Stratis/commit/93b5bf2d38d45dc86c8fca6b141a43b2d4b476c3

**Comment by nomisum** [comment]
https://github.com/gruppe-adler/TvT_BreakingContact.Stratis/issues/103
