### ISSUE TITLE
Funkwagen durch ACE Cookoff extrem schwer zerstörbar

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/TvT_BreakingContact.Stratis#107]
Explodiert selbst nach mehreren Granaten/AT Treffern nicht, da keine Munition im Inventar.

**Comment by nomisum** [comment]
Seriously 👎 

Dann müssen wir wohl Muni reinmachen als Workaround - oder Damage > 0.8 abfangen statt !alive

**Comment by McDiod** [comment]
Tatsächlich gab es dadurch gestern einige interessante Endgefechte. Statt nur einen AT-Schützen bis auf 150m ranzubringen, musste man wirklich die Kontrolle über den Funkwagen haben um ihn zu zerstören.

**Comment by McDiod** [comment]
Gerade nochmal getestet, `damage` ist unzuverlässig. `funkwagen getHit "karoserie" == 1 && funkwagen getHit "motor" == 1` würde funktionieren. 

Entweder hat Blufor dann direkt gewonnen, oder man macht noch vorher `[funkwagen] call ace_cookoff_fnc_cookOff` und wartet bis `funkwagen damage == 1`. Dass der so spektakulär abraucht ist zwar n bisschen unrealistisch, aber eine gute Bestätigung für die Spieler. "Aha, Funkwagen brennt ab, wir haben gewonnen."

**Comment by nomisum** [comment]
finde ich gut. wenn du bock hast, bau es ein. ist grad out of scope für meine free time ⏳

**Comment by nomisum** [comment]
Btw wenn es die Gefechte spannender macht, könnte man einen Eroberungsmodus einbauen. So dass die Amis den Funkwagen "lebendig" haben wollen, d.h. maximal die Reifen dürfen kaputt sein, damit sie die Technik untersuchen können.

**Comment by McDiod** [comment]
fixed in 5f3dbe9
