### ISSUE TITLE
Eroberungsmodus

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/TvT_BreakingContact.Stratis#109]
@nomisum sagte:
>Btw wenn es die Gefechte spannender macht, könnte man einen Eroberungsmodus einbauen. So dass die Amis den Funkwagen "lebendig" haben wollen, d.h. maximal die Reifen dürfen kaputt sein, damit sie die Technik untersuchen können.

**Comment by nomisum** [comment]
first test can start soon

**Comment by nomisum** [comment]
wörks fine
