### ISSUE TITLE
Bugs MP Test

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/TvT_BreakingContact.Stratis#112]
- [x] Kaufmenü öffnet sich bei allen?
- [x] Fortifications nicht zugreifbar?
- [x] (Kisten kaufen) ewig ordering (evtl 60s Delay?)
- [x] Spawnpad verwischen
- [x] SendeRelay fehlt am Fahrzeug
- [x] localization buy menu

**Comment by nomisum** [comment]
![isamu](https://cloud.githubusercontent.com/assets/500164/22446259/fd444f9e-e74b-11e6-9ace-52dc51dfeaae.JPG)

**Comment by nomisum** [comment]
beim kaufmenü bug bräuchte ich evtl debug-unterstützung @Fusselwurm , ich vermute das hängt irgendwie mit https://github.com/gruppe-adler/TvT_BreakingContact.Stratis/blob/master/grad_buymenu/definitions/_dialogs.hpp#L8 zusammen und war in rattrap schon n problem iirc.

auch wärs schön, wenn alle alles kaufbare sehen könnten, nur mit disabled buttons.

**Comment by Fusselwurm** [comment]
Bin grad nich aufm laufenden… sollte nicht das mcdiodsche Kaufmenü benutzt werden irgendwann?

**Comment by nomisum** [comment]
das designmäßig so zu pimpen dass ich zufrieden bin seh ich grad nich realistisch in den nächsten 3 monaten (slotting, telephone, rattrap fixen). deshalb ist jetzt erstma das menü von rattrap portiert.
