### ISSUE TITLE
think about AA truck

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/TvT_BreakingContact.Stratis#114]
benefits:
* size of the truck makes AA a valid target to destroy
* reload times of manpads are longer than igla shouldered

downsides:
* extra vehicle in buy menu
* seeing no truck means in most cases air-defenseless opfor

**Comment by Fusselwurm** [comment]
accurate fire on > 1km would be very strong, but I /think/ the dispersion was quite high. in which case :+1: for a spray-and-pray vehicle ^^

**Comment by nomisum** [comment]
actually salbei wanted to mount a manpad via attachto on a regular kamaz @Fusselwurm 

the AA gun would (probably) be imba against infantry

**Comment by Fusselwurm** [comment]
fixed MANPAD on vehicle :-1: 

* vehicle is a bigger target
* manpad would be unrecoverable if vehicle is destroyed or damaged
* less surprising for air units
* more expensive (it doesnt make sense to make it cheaper than the manpad without vehicle)

but :+1: 

* you could give it a larger amount of ammunition

in any case, that thing would lead to a stronger rock-paper-scissors factor which weakens the infantry-emphasizing nature of arma. meh.

**Comment by nomisum** [comment]
i will probably implement a dedicated AA-infantry slot similar to the RPG slot. ammo truck will only contain more rockets, same as with RPGs. so AA spam (3 shots were fired almost simultanously last game, bc 3 defense packs) wont be possible anymore.

**Comment by McDiod** [comment]
In that case blufor will have certainty about the AA situation though, because they can see the slot list.

**Comment by Fusselwurm** [comment]
the same is already true for AT, havent heard anyone complain about it yet

**Comment by McDiod** [comment]
The same is also true for rifles - but neither can be compared with AA. There is no cover in the air, there is no effective range limit, and there is no "missing" with AA - only evasion. As soon as you see an enemy AA soldier slotted, you absolutely have to play around it.

Would take some depth out of the mission imo.

**Comment by nomisum** [comment]
I'm not decided on the whole topic yet. Good points. Only thing for sure is the removal from the defence crate.

We already have seen a different, more careful use of the MH6 after the introduction of AA. With the knowledge of "no AA slotted", we might see more bold attacks again I presume. (if no AA is slotted)

Maybe this can be countered again by providing a 50:50 chance of a 1 single AA tube vs. 1 single RPG tube in the ammo truck. So you never can be sure there is no AA in the game at all.

**Comment by nomisum** [comment]
quite perfect position on flatbed kamaz: 
`igla attachto[kamaz,[0.4,-1.5,0.58]];`
