### ISSUE TITLE
Spawn Blufor without them knowing where Opfor is

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/TvT_BreakingContact.Stratis#13]

**Comment by Fusselwurm** [comment]
if you do not want to give blufor hints about the location, that either eliminates the minimal spawn distance, or forces you to use pre-defined zones (like western half for blufor, eastern half for opfor) as separate spawn areas. 

are you sure?

**Comment by nomisum** [comment]
SHK Pos will search in between minimal/maximum spawn range as before, also preferring roads in 360 degrees around blufor position.

Only difference is, blufor cant storm the front instantly but has to scout first (or wait for the first radio signal).

**Comment by Fusselwurm** [comment]
so… you dont choose your location any more?

**Comment by nomisum** [comment]
only opfor chooses, blufor will spawn immediately after opfor - eliminating additional waiting time and streamlining the setup.

**Comment by Fusselwurm** [comment]
ah. nice :) :+1:
