### ISSUE TITLE
cannot enter friendly vehicles after killing civilian 

### ISSUE THREAD

**Issue by Fusselwurm** [gruppe-adler/TvT_BreakingContact.Stratis#146]
today i killed a civ and couldn't mount a vehicle occupied by one of my mates. no problem, however, when it was empty. 

looks like it's possible to go RENEGADE really easy. imho that should not happen.

**Comment by nomisum** [comment]
i couldve sworn handlerating is already in... apparently not.

**Comment by nomisum** [comment]
fixed in one of the last commits
