### ISSUE TITLE
bug in GRAD_tracking_fnc_mainLoop

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/TvT_BreakingContact.Stratis#155]
[Here](https://github.com/gruppe-adler/TvT_BreakingContact.Stratis/blob/master/grad_tracking/init.sqf#L58) it has to be:

```sqf
[
	_radioVeh, 
	_terminal, 
	{MISSION_COMPLETED}
] call GRAD_tracking_fnc_mainLoop;
```

and [here](https://github.com/gruppe-adler/TvT_BreakingContact.Stratis/blob/master/grad_tracking/functions/server/fn_mainLoop.sqf#L20) it has to be:

```sqf
if (call _endCondition) exitWith { [_handle] call CBA_fnc_removePerFrameHandler; };
```

otherwise `_endCondition` in `fnc_mainLoop` is always `false`. Might not cause any actual problems, just something that I stumbled upon.

**Comment by nomisum** [comment]
implemented in https://github.com/gruppe-adler/TvT_BreakingContact.Stratis/commit/10d5d94259678826bb00ec214d09aea2d9971390
