### ISSUE TITLE
remove logo overlay over replay

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/TvT_BreakingContact.Stratis#159]

**Comment by nomisum** [comment]
adler overlay appears 2 times

**Comment by McDiod** [comment]
also, overlay should be slightly longer now that there is more text to read

**Comment by nomisum** [comment]
i couldnt find the cause for displaying the overlay 2 times

**Comment by McDiod** [comment]
Apparently this only happens with the `BLUFOR_ELIMINATED` and `OPFOR_ELIMINATED` win conditions, which leads me to believe that the cause has to be [this](https://github.com/gruppe-adler/TvT_BreakingContact.Stratis/blob/master/BC_objectives/functions/server/fn_loopConditions.sqf#L16). The public variable probably gets broadcasted twice [here](https://github.com/gruppe-adler/TvT_BreakingContact.Stratis/blob/master/BC_objectives/functions/server/fn_waitingForUnconscious.sqf#L12).

Easy fix would be to use [`CBA_fnc_publicVariable`](http://cbateam.github.io/CBA_A3/docs/files/network/fnc_publicVariable-sqf.html) which only broadcasts if the value changed.

**Comment by nomisum** [comment]
sounds good.
