### ISSUE TITLE
error in fnc_createEntries

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/TvT_BreakingContact.Stratis#160]
On other clients, when BLUFOR commander buys.

```sqf
21:59:19 "refreshing gui"
21:59:19 Suspending not allowed in this context
21:59:19 Error in expression <Each _dummyPictureIDCs;
};


waitUntil {!isNull _createdGui};
randIDC = 1000;
ra>
21:59:19   Error position: <!isNull _createdGui};
randIDC = 1000;
ra>
21:59:19   Error Generic error in expression
21:59:19 File mpmissions\__CUR_MP.Altis\grad_buymenu\functions\player\fnc_createEntries.sqf, line 32
21:59:19 "sort after [""mrzr4"",""hmmwv_m2"",""m113"",""ammocar"",""melb"",""mh60"",""recon_box""]"
```

**Comment by nomisum** [comment]
i dont know how to fix this. nullCheck is built in to fix a "undefined createdgui"

**Comment by McDiod** [comment]
`waitUntil` doesn't work because unscheduled [here](https://github.com/gruppe-adler/TvT_BreakingContact.Stratis/blob/caf74b337aa5ad403f422acbd18abfcfed71b2c5/grad_buymenu/openMenu.sqf#L24) and [here](https://github.com/gruppe-adler/TvT_BreakingContact.Stratis/blob/caf74b337aa5ad403f422acbd18abfcfed71b2c5/grad_buymenu/functions/player/fnc_RefreshGui.sqf#L5)

**Comment by nomisum** [comment]
i dont know if its safe to just use spawn instead of call. might be worth a try.

**Comment by McDiod** [comment]
spawn won't work because you want to return the gui

**Comment by nomisum** [comment]
then just exitwith when isnull might be the best

**Comment by McDiod** [comment]
Yea, should probably `exitWith {displayNull}` so that it doesn't return nil.

**Comment by nomisum** [comment]
try to fix in https://github.com/gruppe-adler/TvT_BreakingContact.Stratis/commit/0800681aac4214f238bb3753ca720ed3f72ccb3e
