### ISSUE TITLE
bug in BC_objectives_fnc_waitingForUnconscious

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/TvT_BreakingContact.Stratis#162]
`_bool` [here](https://github.com/gruppe-adler/TvT_BreakingContact.Stratis/blob/cc65448e02af3489ea9b2c4868bd2f3242f33998/BC_objectives/functions/server/fn_waitingForUnconscious.sqf#L3) will always have the initial value of the variable behind `_varname`. Has to be

```sqf
private ["_bool"];

for [{_i=0}, {_i<20}, {_i=_i+1}] do
{
        _bool = call compile _varName;
	if (!_bool) exitWith {};
	sleep 0.5;
};
```

**Comment by nomisum** [comment]
fixed in https://github.com/gruppe-adler/TvT_BreakingContact.Stratis/commit/fde1cd4ee93be13db969222b8f4526dd18f9cfc7#diff-2e3eb892ba541d4039b2d06b0b77c15f
