### ISSUE TITLE
Virtual Spectator slots

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/TvT_BreakingContact.Stratis#166]
@fraggi would like to film on Monday.

- [x] implement Virtual Spectator slots
- [x] test if VS clashes with ACE-Spectator
- [x] check if VSs are in `playableUnits` ~and if so, if there are any problems with grad-loadout~ - no
- [x] check if VSs are in `allPlayers` and if so, if there are any problems with grad-loadout
- [x] test who VSs can talk to via TFAR
- [ ] check if VSs are visible in replay

**Comment by nomisum** [comment]
if it clashes we could provide civilian slots and send them instantly to ace spectator.

does virtual spectator have any benefits like smoother camera control?

**Comment by McDiod** [comment]
I think ace spectator controls are hardcoded so you can't use a controller to move the cam smoothly. Other than that no benefits as far as I'm aware.

**Comment by McDiod** [comment]
Mission will currently not end, because grad_replay doesn't start. I have a feeling it's because of the virtual spectator slots.

**Comment by nomisum** [comment]
yes, end condition checks for playableunits (to make testing with Bots easier).

**Comment by McDiod** [comment]
VSs are not in playableUnits though. Tested everything except for replay. No problems. Reverting the VSs still didn't solve the mission end bug, so it it works again when you build it, we can leave it in.

**Comment by nomisum** [comment]
![20170423160653_1](https://cloud.githubusercontent.com/assets/500164/25314172/3ba27124-283f-11e7-9654-2e2f8422b902.jpg)

**Comment by nomisum** [comment]
```
16:08:53 Error in expression <HitPoints = getAllHitPointsDamage _unit select 2;

_unit setDamage _damage;

{
_>
16:08:53   Error position: <select 2;

_unit setDamage _damage;

{
_>
16:08:53   Error Zero divisor
16:08:53 File z\ace\addons\medical\functions\fnc_setStructuralDamage.sqf, line 18
```

**Comment by nomisum** [comment]
```
OPFOR_PRE_ELIMINATED = ({side _x isEqualTo east && alive _x} count allUnits == 0);
BLUFOR_PRE_ELIMINATED = ({side _x isEqualTo west && alive _x} count allUnits == 0);
```

instead of 
```
OPFOR_PRE_ELIMINATED = ({side _x == east && alive _x} count allUnits == 0);
BLUFOR_PRE_ELIMINATED = ({side _x == west && alive _x} count allUnits == 0);
```

COULD have fixed the issue. BUT we only tested opfor death and VS seems to be counted as WEST:
```
16:08:22 "west units alive: 2"
16:08:22 "east units alive: 0"
```

needs further investigation

**Comment by nomisum** [comment]
seems to work now
