### ISSUE TITLE
Preparation Time

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/TvT_BreakingContact.Stratis#167]
* missionparameter, off by default
* shows countdown on mission start
* players may only leave start area after countdown runs out >> teams have some time to buy stuff, plan, organize
* no hard enforcement of the rule above as to not create any unnecessary sources of errors

**Comment by McDiod** [comment]
What's the best way to do this?

Remote execution would make sure there are no problems with JIP and that time stays synchronized. Are there any hints during mission start that this solution would interfere with?

```sqf
//PFH on server, once every second
format ["Game starts in: %1",_timeleft] remoteExec ["hint",0,false];
```

**Comment by nomisum** [comment]
`[{hintSilent "Blufor Spawn successfully found.";},"BIS_fnc_spawn",true,true] call BIS_fnc_MP;`

iirc teleport hint uses the ACE textfield

**Comment by McDiod** [comment]
Hm, I think I will just make a little `cutRsc` title on the right side of the screen.

Where do I put it? BC_objectives folder?

**Comment by nomisum** [comment]
fine for me

**Comment by McDiod** [comment]
tested in multiplayer
