### ISSUE TITLE
implement Opfor defense pack again?

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/TvT_BreakingContact.Stratis#173]
Now that the AA Truck is gone the old defense pack could be used again.

### Possible contents:
* AA Turret
* static DshKM
  * static DshKM could be removed from Ammotruck?
  * or maybe leave DshKM in Ammotruck so you can buy the defense pack to get extra more defense to the maxXx?
* some more grad-fortifications
  * mostly sandbags
  * enough to build a small, fortified position for AA and DshKM

### Old files:
* [buymenu](https://github.com/gruppe-adler/TvT_BreakingContact.Stratis/blob/5f3dbe9957740df8d263ae76d7de548b93340d9a/spawn/gui/addPublicVariableEventhandler.sqf#L164)
* [pic](https://github.com/gruppe-adler/TvT_BreakingContact.Stratis/blob/5f3dbe9957740df8d263ae76d7de548b93340d9a/spawn/gui/pic/rus_static_mg.paa)

**Comment by nomisum** [comment]
i'd like to use the box slots for vehicles too in the future. so you get a low level transport filled with stuff and dont have to fiddle with boxes so much. so yes, defence pack is making a comeback in some form or another.

**Comment by nomisum** [comment]
i dont plan to do any rebalancing now, should consolidate stable first
