### ISSUE TITLE
Test ACE Spectator (or implement CSSA3)

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/TvT_BreakingContact.Stratis#18]

**Comment by nomisum** [comment]
missing entry in description.ext:

```
respawn = 0;
respawnDelay = 3;
respawnTemplates[] = {"ace_spectator"};
respawnTemplatesWest[] = {"ace_spectator"};
respawnTemplatesEast[] = {"ace_spectator"};
```

**Comment by Fusselwurm** [comment]
afaik kannste die …West und …East weglassen, wenn das allgemeine respawnTemplate gesetzt ist

**Comment by nomisum** [comment]
ace spectator should be reverted to CSSA3

reason: quite unclear in calling, CSSA3 has smooth camera movement (LMB+RMB), CSSA3 has points above heads, CSSA3 is able to hide interface completely, CSSA3 is performant
