### ISSUE TITLE
Bugs 24.07

### ISSUE THREAD

**Issue by AdlerSalbei** [gruppe-adler/TvT_BreakingContact.Stratis#188]
- [ ] replace AT-4 with SMAW becouse Opfor can spawn 3 BRDM

**Comment by nomisum** [comment]
BRDM will be nerfed

**Comment by AdlerSalbei** [comment]
Us is then still underequip on AT weapons, becouse RU has an RPG-7 with 3 Missiles, but blufor only gets a AT-4. Good luck stoping a BRDM, you need 2 AT-4 shots to destroy it.

**Comment by nomisum** [comment]
you only need assault rifles to destroy the tires. then its a static PKT turret with a really exposed gunner who has abysmal rotation speed/firing angles.

SMAW is heavy as shit. if its really necessary to give blufor more AT, which is doubtful, i would raise the amount of native AT slots (which would make the ammo truck more or less useless).
