### ISSUE TITLE
GRAD Loadout Problem (only Blufor Woodland)

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/TvT_BreakingContact.Stratis#203]
maybe some bug due to new grad loadout version

**Comment by McDiod** [comment]
[Hier](https://github.com/gruppe-adler/TvT_BreakingContact.Stratis/blob/master/loadouts/US_Woodland.hpp) wird nicht richtig geerbt. Unsicher wie es jemals funktioniert hat ¯\\_(ツ)_/¯
```
class Type: Type {
		class Soldier_F: Soldier_F {
			vest = "rhsusf_spc";
		};
		class Soldier_AR_F: Soldier_AR_F  {
			vest = "rhsusf_spc_mg";
		};
```

**Comment by nomisum** [comment]
HMPF

**Comment by nomisum** [comment]
fixed https://github.com/gruppe-adler/TvT_BreakingContact.Stratis/commit/96cf5a708e4e4785b73af46590a745bca0a5a6c7#diff-f5bd6b9ec981974e7dfcee08777f25c1

**Comment by McDiod** [comment]
Einheitentyp Klassen müssen auch erben `class Soldier_F: Soldier_F`

**Comment by nomisum** [comment]
Ach verdammt. Das ist nur wegen @Synch2k , der unbedingt andere Westen wollte :D :D *blame*

**Comment by nomisum** [comment]
https://github.com/gruppe-adler/TvT_BreakingContact.Stratis/commit/02ba9218352400686025d42ea174b739ffe6bc82
