### ISSUE TITLE
Weitere Ideen

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/TvT_BreakingContact.Stratis#205]
* KPZ für Blufor
* Was schnelles billigeres für Opfors als Tigr
* Andere AK (mit anderem Zeroing < 300m)
* Optional Helmets for Commanders

**Comment by McDiod** [comment]
AK kann man auf 100m zeroen mit *page up* :>

**Comment by nomisum** [comment]
obsolete mit ainers loadout changes 🔜
