### ISSUE TITLE
No per player bonus

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/TvT_BreakingContact.Stratis#206]
Makes planning of vehicles more predictable.

(Downside you have to think more about how many players need a vessel - minimum Money)

**Comment by McDiod** [comment]
Maybe go from *money per player* to *money per X players* so for example every 5 players give you 1000 Cr. Would make it more predictable while keeping scalability.

**Comment by nomisum** [comment]
Interesting idea, though 5 players more or less is no exception either. Maybe 10 is better to estimate.

**Comment by nomisum** [comment]
Or even make it dependent on amount of chosen SQL / TL slots, haha

McDiod <notifications@github.com> schrieb am Di., 27. März 2018, 09:47:

**Comment by nomisum** [comment]
not relevant without money 🔜
