### ISSUE TITLE
grad-fortifications veraltet

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/TvT_BreakingContact.Stratis#212]
Aktuell ist 0.6.3, installiert ist 0.3.6. Keine Ahnung, warum er das als nicht kompatibel ansieht. Einfach immer die neueste Version laden wäre `">0.0.1"`. Skriptfehler vom TTT Spiel (04.06.18) ist damit behoben.

https://github.com/gruppe-adler/TvT_BreakingContact.Stratis/blob/master/package.json#L8

https://github.com/gruppe-adler/grad-fortifications/releases

**Comment by nomisum** [comment]
https://github.com/gruppe-adler/TvT_BreakingContact.Stratis/commit/5e37ec0562f5447bbce12b54659b49c0796858e2
