### ISSUE TITLE
LR + SW not compatible

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/TvT_BreakingContact.Stratis#221]
why the hell, since when

**Comment by dedmen** [comment]
which radios exactly?

**Comment by nomisum** [comment]
tf_rt1523g_big_bwmod & 148er

**Comment by dedmen** [comment]
TFAR_rt1523g_big_bwmod == "tf_west_radio_code"
148 == "tf_independent_radio_code"


mr3000_bwmod == "tf_west_radio_code"
fadak == "tf_east_radio_code"

Has always been like that.

**Comment by nomisum** [comment]
maybe I had overrides once, idk

Dedmen Miller <notifications@github.com> schrieb am Di., 4. Sep. 2018,
07:56:
