### ISSUE TITLE
Waffe austauschen

### ISSUE THREAD

**Issue by Eras308** [gruppe-adler/TvT_BreakingContact.Stratis#223]
Waffe hat einen Frontgriff, der nicht angezeigt, welcher aber gegriffen wird. Macht das Sinn? Bitte die Waffe austauschen. Position war AT-Schütze.

https://cdn.discordapp.com/attachments/291004636612263936/523998211099066368/20181216222329_1.jpg
https://cdn.discordapp.com/attachments/291004636612263936/523998217885581318/20181216222331_1.jpg
https://cdn.discordapp.com/attachments/291004636612263936/523998223552086016/20181216222342_1.jpg
https://cdn.discordapp.com/attachments/291004636612263936/523998226320457749/20181216222347_1.jpg

**Comment by nomisum** [comment]
rhs seems to have changed classnames. fixed in https://github.com/gruppe-adler/TvT_BreakingContact.Stratis/commit/43eb09b6866ca765fcd9b5ab573d95978f51c1c6
