### ISSUE TITLE
Add Zeus Capability for Admin

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/TvT_BreakingContact.Stratis#24]
- [x] Add Zeus Capability for Admin

**Comment by Fusselwurm** [comment]
kann man zeusfähigkeiten nachträglich auf jemanden raufsetzen? dann kann der admin sich die fähigkeit in der mission ad-hoc geben/wegnehmen, und wir brauchen hier nur nen scriptschnipsel bzw ne vorbereitete funktion

**Comment by nomisum** [comment]
ja, müsste gehen, aber is umständlich.

warum sollte der admin die fähigkeit abgeben? kann sich ja ausloggen und ein anderer einloggen, schon ists der andere.
