### ISSUE TITLE
issues from tembelan round

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/TvT_BreakingContact.Stratis#240]
- [x] black screen on jip (@DerZade)
- [x] black screen
- [x] m249 ammobearer wrong ammo and not enough ammo for himself
- [x] map schließt als jip nicht automatisch
~~- [ ] wrong spawn position (connor in water)~~

**Comment by nomisum** [comment]
Wünsche: 2. Runde TvT mit 4x 10 in meinen Augen besser--> mehr zeit für blufor ohne unnötig lange standzeiten
opfor HMG mehr munition da viel ungenauer als us pendant

**Comment by McDiod** [comment]
`_intervals` und `_min` scheint hier nil zu sein:
https://github.com/gruppe-adler/TvT_BreakingContact.Stratis/blob/154478ca63126ce5e165b50bba1fa90884b99603/BC_objectives/functions/common/fn_init.sqf#L16

Taskbeschreibung ist `... any in any mins...` oder so.

**Comment by nomisum** [comment]
> 
> 
> `_intervals` und `_min` scheint hier nil zu sein:
> 
> [TvT_BreakingContact.Stratis/BC_objectives/functions/common/fn_init.sqf](https://github.com/gruppe-adler/TvT_BreakingContact.Stratis/blob/154478ca63126ce5e165b50bba1fa90884b99603/BC_objectives/functions/common/fn_init.sqf#L16)
> 
> Line 16 in [154478c](/gruppe-adler/TvT_BreakingContact.Stratis/commit/154478ca63126ce5e165b50bba1fa90884b99603)
>  private _tasksMain = [_intervals, _min] call BC_objectives_fnc_createTaskMain; 
> 
> Taskbeschreibung ist `... any in any mins...` oder so.

🤔  das ging schonma
