### ISSUE TITLE
Nerf Heli

### ISSUE THREAD

**Issue by AdlerSalbei** [gruppe-adler/TvT_BreakingContact.Stratis#242]
Der dauerhaft kreisende Heli sorgt dafür das Positinieren der eigenen Truppen kaum eine Rolle spielt und man kaum davon kommen kann.

Vorschläge zur Lösung:
- Fuel limitieren mit Fuelbladder oder Fueltruck
- Heli entfernen

**Comment by AdlerSalbei** [comment]
Für die Fuel Limitierung könnte man die menge so einstellen das der Heli nur ca 10min fliegen kann. Dann noch ein Fueltruck dazu und eine Refuelzeit von 5min+. So kann der Hubschrauber nicht konstant kreisen und Opfor hat die Chance durchzubrechen und weg zu kommen.

**Comment by nomisum** [comment]
done in https://github.com/gruppe-adler/TvT_BreakingContact.Stratis/releases/tag/2.4.2
