### ISSUE TITLE
Crew seat counter does not go down when vehicles a removed from list

### ISSUE THREAD

**Issue by AdlerSalbei** [gruppe-adler/TvT_BreakingContact.Stratis#253]
![20191122200530_1](https://user-images.githubusercontent.com/12427159/69453140-8e630980-0d63-11ea-9cae-e7e101a6752a.jpg)

**Comment by nomisum** [comment]
might be fixed with https://github.com/gruppe-adler/TvT_BreakingContact.Stratis/commit/84281aa416528df463ce4d20225345fb4fb33ee7
