### ISSUE TITLE
Replay Startet nach ladebalken nicht

### ISSUE THREAD

**Issue by AdlerSalbei** [gruppe-adler/TvT_BreakingContact.Stratis#254]

**Comment by nomisum** [comment]
details? hatten wir nie

**Comment by McDiod** [comment]
Steht `"Waiting for players timed out. Missing players: %1"` im Serverlog?

https://github.com/gruppe-adler/grad-replay/issues/33

**Comment by nomisum** [comment]
Zuviel Daten vmtl? Evtl Ticktime automatisch nach Playercount am Anfang anpassen 🤔

**Comment by McDiod** [comment]
>Zuviel Daten vmtl?

Weiss nicht, bei zu vielen Daten hätte ich eher erwartet, dass er komplett abstürzt, so wie beim letzten Mal. Unmöglich ist es aber nicht.

**Comment by nomisum** [comment]
schätze eher ein grad-replay issue als ein BC issue. keine möglichkeit und keine idee für repro.
