### ISSUE TITLE
"Players dead" triggers don't work if there are non-player units alive

### ISSUE THREAD

**Issue by dedmen** [gruppe-adler/TvT_BreakingContact.Stratis#260]
In my test, seems like some mod is spawning a blufor non-player unit. When all players are dead, that non-player unit still counts as "blufor unit is alive" and the end condition doesn't trigger.

**Comment by nomisum** [comment]
should be fixed with https://github.com/gruppe-adler/TvT_BreakingContact.Stratis/pull/265
