### ISSUE TITLE
evaluate better fortification building system regarding ACE sandbags

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/TvT_BreakingContact.Stratis#41]
possible snap-to-scripts:

Epoch (A2) http://epochmod.com/forum/index.php?/topic/6036-release-build-snapping-extended-v16-updated-02202014/

iBuild (A3) http://www.armaholic.com/page.php?id=27078

**Comment by nomisum** [comment]
@McDiod how about implementing your fortification stuff?

**Comment by McDiod** [comment]
Sure. But demolition is currently just an ACE-Interaction with an ACE-Progressbar. I haven't found a good way to handle explosions.
