### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/TvT_BreakingContact.Stratis#52]
- [x] Rifleman-Slot mit falscher Funke? Opfor
- [x] 2 Leute nicht teleported
- [x] countdown nach bewusstlosigkeit
- [x] CSSA3 Bug ---> rausschmeißen, mit Vanilla Spec / ACE3 ersetzen tbd
- [x] BFT enablen
- [x] Chinook rein
- [ ] Fastroping enablen
- [x] spawnPad verwischen nur lokal
- [ ] kein Opfor Spawn südlich Devils Castle
- [x] check ace module for extra tires in cargo
- [x] TFAR spec beim replay

**Comment by AdlerXiviD** [comment]
Spawnpunkt "H" lässt sich nicht verwischen, bzw nur lokal

**Comment by nomisum** [comment]
@McDiod @Fusselwurm ich brääaeuchte noch paar meinungen, warum manche leute manchmal nicht teleportiert werden. trat jetzt mit dem aktuellen code wieder auf bei meat.

**Comment by meat147** [comment]
Zum Thema Fast Roping bitte warten bis der Neue ACE Release draußen ist. :)

**Comment by nomisum** [comment]
@meat147 anders wars nich geplant ;)
