### ISSUE TITLE
"Truck zerstören" ACE-Interaktion für Blufor

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/TvT_BreakingContact.Stratis#56]
ACE Interaktion für Blufor am Funktruck, die den Truck zerstört. ACE Progressbar, Dauer vielleicht 1 min?

Hintergrund: Blufor konnte heute unentdeckt zum Funktruck kommen, hatte aber keine Möglichkeit ihn zu zerstören. So wird Opfor bestraft, wenn sie zu lange die unmittelbare Deckung des Trucks vernachlässigen.

**Comment by nomisum** [comment]
ready to test
