### ISSUE TITLE
Letzter "OPFOR has already sent X" hint deutlicher

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/TvT_BreakingContact.Stratis#59]
- [x] make sending message more in your face. maybe add a sound effect?

Bei 90% oder so. Vor lauter Spannung heute übersehen.

**Comment by nomisum** [comment]
regenbogenfarben? ;) ist momentan auch "nur" normale hintlänge.

**Comment by Fusselwurm** [comment]
IMO, this game mode is not about last-second suicide dashes to disable the radio truck.
I'd rather have people lose the match if in doubt, maybe even withdraw, and survive.

So I'm opposed to anything that marks the time more prominently, or that approaches having a countdown, or anything like that. 
BLUFOR should of course have a rough idea if they have 10 or rather 20 minutes left. – The only problem with the current system I'm ready to admit is that it always shows a *fraction* of some variable time. There's a big difference if you have 10% left of 90 minutes or of 30 minutes. 

How about we start displaying a time in absolute terms? Maybe round up/down a bit, make it a bit fuzzy: `OPFOR needs only five more minutes to complete their broadcast!` , and actually they might take 3 minutes, or 7, or anything in between.

**Comment by McDiod** [comment]
Is this English only now that it's on Armaholic? :)

I agree with Fussel in that we don't need a countdown. But during the end game when you expect contact behind any corner the 90% hint is too easily missed for how much it matters in decision making - especially so at night, when the hint box is black on black.

A subtle alert sound would suffice imo.

**Comment by nomisum** [comment]
sound effect of normal msgs added
