### ISSUE TITLE
Remove Wirecutter/Engineer Slot

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/TvT_BreakingContact.Stratis#60]
- [x] remove wirecutter
- [x] remove slot / exchange for sth else

**Comment by Fusselwurm** [comment]
fixed in dec9a8814e45007ba7aac8080faace0b3c8a8997 , so... can we close this issue? @nomisum

**Comment by nomisum** [comment]
should be testet first maybe :stuck_out_tongue_winking_eye:
