### ISSUE TITLE
Flashlights for all Opfor

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/TvT_BreakingContact.Stratis#63]
- [x] loadout gives everyone. 
- [x] check all weapons for compatibility

**Comment by nomisum** [comment]
loadout gives everyone. todo: check all weapons for compatibility

**Comment by Fusselwurm** [comment]
see f79113f37f32650420afc36c689b832b8a81626b  -- you've got to give a AKM compatible RHS flashlight  for it to work. 

Unfortunately, the GP25 weapon variants dont seem to be supported by that flashlight :(
